name: CI

on: 

  push:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3
      - name: Set trace-start
        id: set-trace-start
        run: |
           echo ::set-output name=trace-start::$(date +%s)

      - name: build
        run: |
          echo "building"
          
      - name: SonarCloud Analysis
        run: |
         chmod +x gradlew
         ./gradlew buil sonar -Dsonar.token=${{ secrets.TOKENSONARV1 }}
     
    outputs:
      trace-start: ${{ steps.set-trace-start.outputs.trace-start }}
